plugins {
    id 'java'
}

group = 'graphs'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }

    test {
        java {
            srcDirs = ['test/java']
        }
    }
}

test {
    useJUnit()
}